/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCategory: typeof import('./components/app-category/app-category.vue')['default']
    AppGuessLike: typeof import('./components/app-guess-like/app-guess-like.vue')['default']
    AppScrollView: typeof import('./components/app-scroll-view/app-scroll-view.vue')['default']
    AppShopItemV1: typeof import('./components/app-shop-item-v1/app-shop-item-v1.vue')['default']
    AppSwiper: typeof import('./components/app-swiper/app-swiper.vue')['default']
    AppTab: typeof import('./components/app-tab/app-tab.vue')['default']
    CategoryGoodsSkeleton: typeof import('./pages/category/components/category-goods-skeleton.vue')['default']
    CategorySkeleton: typeof import('./pages/category/components/category-skeleton.vue')['default']
    HomeCategory: typeof import('./pages/home/components/home-category.vue')['default']
    HomeHeader: typeof import('./pages/home/components/home-header.vue')['default']
    HomeRecommend: typeof import('./pages/home/components/home-recommend.vue')['default']
    HomeSkeleton: typeof import('./pages/home/components/home-skeleton.vue')['default']
    HotSkeletion: typeof import('./pages/hot/components/hot-skeletion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
